project_name_override: bindings
package_name_override: python_client
package_version_override: 5.2.1
post_hooks:
   - "ruff check . --fix --extend-select I --config ../../ruff.toml"
   - "ruff format . --config ../../ruff.toml"
